services:
  mssql_primary:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mssql_primary
    hostname: mssql_primary
    ports:
      - "1434:1433" # Primary Port
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    volumes:
      - mssql_primary_data:/var/opt/mssql
    restart: unless-stopped

  mssql_replica:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mssql_replica
    hostname: mssql_replica
    ports:
      - "1435:1433" # Replica Port
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    volumes:
      - mssql_replica_data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis_sync_state
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mssql_primary
      - mssql_replica
      - redis
    environment:
      - MSSQL_PRIMARY_URL=mssql://sa:Password123!@mssql_primary:1433/testct
      - MSSQL_REPLICA_URL=mssql://sa:Password123!@mssql_replica:1433/testct
      - REDIS_URL=redis://redis:6379
      - SYNC_THREADS=2
      - RUST_LOG=error,backend=info
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  mssql_primary_data:
  mssql_replica_data:
  redis_data:
